[tool.poetry]
name = "python-web-server"
version = "0.1.0"
description = ""
authors = ["Cory Coward <cory@c2softwaresolutions.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
